services:
    terminal42.contao_bynder.picker_provider:
        class: Terminal42\ContaoBynder\Picker\BynderAssetPickerProvider
        arguments:
            - "@knp_menu.factory"
            - "@router"
            - "@security.token_storage"
        tags:
            - { name: contao.picker_provider }

    terminal42.contao_bynder.api:
        class: 'Terminal42\ContaoBynder\Api'
        factory: ['Terminal42\ContaoBynder\Api', createLogged]
        arguments:
            - 'settings' # Set based on configuration in extension
            - "@logger"
        tags:
            - { name: monolog.logger, channel: terminal42.contao_bynder }
        public: true

    terminal42.contao_bynder.image_handler:
        class: Terminal42\ContaoBynder\ImageHandler
        arguments:
            - "@terminal42.contao_bynder.api"
            - "@logger"
            - 'derivativeName' # Set based on configuration in extension
            - 'derivativeOptions' # Set based on configuration in extension
            - 'targetDir' # Set based on configuration in extension
            - "@contao.framework"
            - '%kernel.root_dir%/'
            - '%contao.upload_path%'
        tags:
            - { name: monolog.logger, channel: terminal42.contao_bynder }
        public: true
