services:
    terminal42.contao_bynder.picker_provider:
        class: Terminal42\ContaoBynder\Picker\BynderAssetPickerProvider
        arguments:
            - "@knp_menu.factory"
            - "@router"
            - "@security.token_storage"
        tags:
            - { name: contao.picker_provider }

    terminal42.contao_bynder.api:
        class: 'Terminal42\ContaoBynder\Api'
        factory: ['Terminal42\ContaoBynder\Api', create]
        arguments:
            - 'settings' # Set based on configuration in extension
        public: true

    terminal42.contao_bynder.image_handler:
        class: Terminal42\ContaoBynder\ImageHandler
        arguments:
            - "@terminal42.contao_bynder.api"
            - "@logger"
            - 'derivativeName' # Set based on configuration in extension
            - 'derivativeOptions' # Set based on configuration in extension
            - 'targetDir' # Set based on configuration in extension
            - "@contao.framework"
            - '%kernel.project_dir%'
            - '%contao.upload_path%'
        tags:
            - { name: monolog.logger, channel: terminal42.contao_bynder }
        public: true

    Terminal42\ContaoBynder\Controller\ApiController:
        public: true
        arguments:
            - "@terminal42.contao_bynder.api"
            - "@database_connection"
            - "@contao.framework"
            - "@terminal42.contao_bynder.image_handler"

    Terminal42\ContaoBynder\Controller\PickerController:
        arguments:
            - "@contao.framework"
            - "@contao.menu.renderer"
            - "@contao.picker.builder"
        public: true

    Terminal42\ContaoBynder\EventListener\FilesCopyButtonListener:
        public: true
        tags:
            - { name: contao.callback, table: tl_files, target: list.operations.copy.button_callback }
